[theme]
font = "calibri"

[theme.light]
primaryColor = "#1F77B4"
backgroundColor = "#feffff"
secondaryBackgroundColor = "#e0f2fd"
textColor = "#1A1A2E"

[theme.dark]
primaryColor = "#60B8FF"
backgroundColor = "#0f2031"
secondaryBackgroundColor = "#1f3753"
textColor = "#E8EDF5"
